# Generated by Django 5.2.7 on 2025-10-27 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_patients_seen', models.PositiveIntegerField(default=0)),
                ('avg_wait_time_minutes', models.FloatField(default=0.0)),
                ('appointments_today', models.PositiveIntegerField(default=0)),
                ('staff_on_duty', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
